### ISSUE TITLE
can't add collaborators from event details page

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#1114] opened 2021-01-05 16:25 UTC
Getting JSON errors when try to add collaborators on event 201004 on live site

When Dan Grear from NWHC tried to add Charles Sassine as a read/write collaborator to 201004 today he got this error:
Error. Collaborator list not updated. Error message: SyntaxError: Unexpected token T in JSON at position 0

Jenny Chipault went to the event to try it with her permissions and got this error:
Error. Collaborator list not updated. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by JChipault** [comment] 2021-01-05 16:37
Next went to 170970 on the test site and I was able to add an end date and mark the event as complete but I got a JSON error when I tried to add a collaborator

**Comment by JChipault** [comment] 2021-01-05 16:42
Just tried adding a collaborator when creating an event on the test site (so not from the event details page) and that worked fine.

**Comment by JChipault** [comment] 2021-01-05 16:51
Seems possibly related to #1058. This used to just be an issue on the test site but maybe that bug has crept over to the live site

**Comment by JChipault** [comment] 2021-01-05 22:01
@aaronstephenson - tagging you here because I'm not sure if you see new issues in this queue otherwise

**Comment by aaronstephenson** [comment] 2021-01-05 22:21
Thanks @JChipault. After reading this and rereading #1058, this is a duplicate of #1058; essentially, I "fixed" the add collaborators bug earlier in the fall, but that "fix" only worked for new events. The reason is doesn't work for existing events is explained in that issue, but long story short I corrected that problem.

That said, your second comment about updating event 170972 is unrelated to #1058, so I will look into it.

**Comment by JChipault** [comment] 2021-01-06 14:25
@aaronstephenson This is great news! Can you let me know when the fix is pushed?

**Comment by aaronstephenson** [comment] 2021-01-06 17:16
@JChipault I just pushed it to the test server. I wasn't able to SSH onto it last night, but was able to just now.

**Comment by aaronstephenson** [comment] 2021-01-06 17:53
@JChipault I tried the scenario you mentioned above (changing complete to incomplete), and the cause of that problem was the same as #1058, namely updating an event errored because the code snippet for updating collaborators inside the event update code block was causing an error. So that problem is also fixed by the fix for #1058.

**Comment by JChipault** [comment] 2021-01-06 19:14
@aaronstephenson  Looks good for both the collaborators and complete/incomplete issues! Thanks! Next, can you let us know when the fix is pushed to live?

**Comment by aaronstephenson** [comment] 2021-01-06 20:14
@JChipault fix pushed to the production server.

**Closed** 2021-02-17 17:54 UTC
Labels: bug
