### ISSUE TITLE
comment timeline not updating when events are grouped

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#776] opened 2020-01-09 21:50 UTC
If I'm looking at the comment timeline for an event that is grouped with other events, then when I switch to another event in that group by hitting the number in the "Associated Events" area, I still see the comment timeline for the event that I was looking at previously. Put another way, the comment timeline is not refreshing when I toggle among events that are grouped. I think we had a similar issue with the map not refreshing when toggling among events that were grouped so maybe the same code can refresh the comment timeline?

**Comment by BlakeDraper** [comment] 2020-01-10 20:07
I have fixed this by making the tabs default back to the Event Data tab upon loading a new event with this method. It leverages the existing logic that loads/renders the comment timeline when the tab is activated, and also seem more appropriate since any other time a user arrives at the event details page for a new event, the Event Data tab is active. Done in code.

**Comment by BlakeDraper** [comment] 2020-01-13 19:46
Released in v2.11.1

**Closed** 2020-01-13 19:46 UTC
Labels: bug

**Comment by BlakeDraper** [comment] 2020-01-14 15:49
Confirmed functional by NWHC
