### ISSUE TITLE
Prevent test data from populating google analytics

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispers#756] opened 2019-12-13 16:52 UTC
First we'll see if they want a test version of GA.

If not, we will see if we can pull that out into a config file and be read into index. For non-prod environments the id would be `''`, which we tested and does not appear to break anything. We'd push this to test and see if any weirdness happens.

If that no, work we'll just add a new property for test and put that in the config.

**Comment by BlakeDraper** [comment] 2019-12-17 21:07
Clsoed as duplicate of #755

**Closed by BlakeDraper** 2019-12-17 21:07 UTC
