### ISSUE TITLE
Diagnosis pending and undetermined

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#530] opened 2019-03-29 15:19 UTC
The lab requirement for non-suspect species diagnosis is NOT required for 'Pending' or 'Undetermined'.  
Also, only allow selection of 'Pending'  or 'Undetermined' based on event completion (see business rule) at both the species and event levels.

**Comment by BlakeDraper** [comment] 2019-04-04 15:29
Must allow non-suspect without lab for Pending and Undetermined

**Comment by JChipault** [comment] 2019-04-04 19:11
When I start a new event and have it marked as incomplete, the system currently defaults to "undetermined" for event diagnosis when it should default to "pending". Complete events should be "undetermined"

**Comment by BlakeDraper** [comment] 2019-05-20 22:08
Both items fixed in code.

**Closed** 2019-05-22 18:25 UTC
Labels: Event Details Page, Event Submission Page, bug

**Comment by JChipault** [comment] 2019-05-22 22:03
During create event, if event incomplete and I select "pending" as event diagnosis, then I change event to complete, which makes event diagnosis go blank. If I try to save the event I get "Error. Event not Submitted. Error message: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by JChipault** [comment] 2019-05-22 22:08
If event is incomplete, then I can select Pending for event diagnosis (yay!), but if I change event to complete, then the event diagnosis line that used to say Pending just goes blank when it should toggle to Undetermined.

**Comment by BlakeDraper** [comment] 2019-05-22 22:15
@JChipault the blanking is the intended behavior. Pending and Undetermined are actual diagnosis values in the database, so when the Record Status is updated, I change the availability of those with respect to the record status, as requested. 

The user needs to re-select the event diagnosis if they have already selected it and the Record Status then changes. I disagree somewhat philosophically that the value they entered should silently change based on activity elsewhere in the form. This could later confuse the user who thought they selected 'Pending'  and later see the diagnosis as 'Undetermined'. 

As far as the submission error you received after this sequence, I agree that is a bug that should not happen and I will address that.

**Comment by JChipault** [comment] 2019-05-22 22:19
Moved JSON submission error to different github ticket because realized it was happening no matter what type of data I was trying to submit. 

Will play around with this more and factor in your notes about the blank being intentional after I can see what happens when I submit data. Thanks!

**Comment by JChipault** [comment] 2019-05-23 15:50
So if I create an event and do Pending for event diagnosis, then switch status to complete which makes the event diagnosis goes blank, then I can still save the event and I end up with a blank event diagnosis when I look at the event details page, which violates business rules because always have to have an event diagnosis.

**Comment by JChipault** [comment] 2019-05-23 16:44
Also, if I have (for example) trauma as a species diagnosis, still need trauma AND pending/undetermined (depending on record status) available as options at the event level because could be that 1 bird had trauma but I'm not comfortable saying the whole event of 1500 dead birds was due to trauma so would rather have it say Undetermined at event level when I mark the event as complete

**Comment by BlakeDraper** [comment] 2019-05-23 21:57
@JChipault regarding the creation of an event without any event diagnosis, that was indeed a bug Aaron found on the backend, but it was only coincidental with the latest updates to the the way event diagnosis has select has been updated. 

As for the selection of Undetermined/Pending at event level, to clarify, you are talking about the event details page context of an existing event, not the initial creation of an event, correct?

**Comment by JChipault** [comment] 2019-05-23 22:07
Yes, for event details page. Looks like it's functioning as I was hoping on the create event page.

**Comment by BlakeDraper** [comment] 2019-05-24 20:08
@JChipault I have fixed the code such that the record-status-appropriate 'unknown' diagnosis (Pending or Undetermined) remains as an option alongside the constituent species diagnosis. You will see that update with the next release. This will allow for the selection of a Pending event diagnosis. However, per the business rules, a user (even an admin) cannot edit event data other than adding comments after event is marked complete. 

> From business rules: "When the record is marked as "Complete" then lock the data (except the comments and ability to attach artifacts)."  https://github.com/USGS-WiM/whispers/issues/566#issuecomment-492825641

This means a user would never be able to select Undetermined for an existing event because the Add Event Diagnosis interface is locked, per specification. What we do do, however, is change any Pending event diagnosis to Undetermined when an existing event changes status to Complete. It seems like we are going to have a call about all of this Tuesday so we can talk more about this then.
