### ISSUE TITLE
specified URL cannot be found - can't save event

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#712] opened 2019-09-25 15:33 UTC
Was trying to create an event on the live site v2.5.0 in firefox and got this in a toast message when I tried to save the event.

Error. Event not Submitted. Error message: {"Log-Id":"16d690207fd-1fc6e123","Request Time":"2019-09-25 15:20:03 GMT","Error":"The specified URL cannot be found "}

Form Status: VALID

 {
  "event_reference": "",
  "event_type": "1",
  "complete": false,
  "public": true,
  "staff": "4",
  "event_status": "1",
  "legal_status": 1,
  "legal_number": "",
  "new_organizations": [],
  "new_service_request": {
    "request_type": 1,
    "new_comments": [
      {
        "comment": "8 laughing gulls chilled: 6 of these are euthanized (5 with isoflurane R, 1 with beuthanasia IV) and 2 were found dead. All collected 9/23-/94."
      }
    ]
  },
  "new_event_diagnoses": [],
  "new_comments": [],
  "new_eventgroups": [],
  "new_event_locations": [
    {
      "name": "Great Pond Rd, Eastham",
      "start_date": "2019-09-23",
      "end_date": null,
      "country": "30",
      "administrative_level_one": 21,
      "administrative_level_two": 1214,
      "latitude": "41.833611",
      "longitude": "-69.983972",
      "land_ownership": "8",
      "gnis_name": "Great Pond",
      "gnis_id": "616863",
      "site_description": "small, roadside, open sandy beach on freshwater pond. picture provided.",
      "history": "Massachusetts DFW received a call on Sept. 13 from someone reporting about 15 gull mortalities at one location in Andover, MA over the previous 10 days. These gulls showed signs of respiratory distress and then died within a few hours. The carcasses were all bagged and discarded (trash). On Sept. 24, MA DFW reported they are getting additional reports of dead/dying gulls, and this seems to be occurring in multiple locations in Massachusetts.\n\nNine juvenile Laughing Gulls were brought into WildCare (rehabilitator on Cape Cod) on 9/24; 7 of them were euthanized and refrigerated. All of these birds had a broken wing, and they were found underneath a powerline. Submitter suspects the broken wings are from colliding with the powerline but that the birds were likely impaired before that impact.  They were found along an inland pond that can have algal blooms. The 7 euthanized LAGUs were given.04 cc of telazol (intra-muscular) and .5 cc intravenous Buthanasia (intravenous).\n\nThere were additional dead gulls reported along a beach in Chatham, which is the neighboring town.\n\nAdditional laughing gulls were collected 9/24; the only meds they received was isoflourane (inhalation) for euthanasia (they didn’t have a co2 chamber).\n\nSubmitter is checking on water quality in the area.",
      "environmental_factors": "no known environmental factors.",
      "clinical_signs": "dehydrated, weakened, depressed condition. unable to fly. droopy wings on most individuals.",
      "comment": "Medium priority for the submitter because the event is ongoing and ",
      "new_location_species": [
        {
          "species": 297,
          "population_count": null,
          "sick_count": 12,
          "dead_count": 2,
          "sick_count_estimated": 18,
          "dead_count_estimated": null,
          "priority": null,
          "captive": false,
          "age_bias": "3",
          "sex_bias": null,
          "new_species_diagnoses": []
        }
      ],
      "new_location_contacts": [
        {
          "contact": 5610,
          "contact_type": 1
        }
      ]
    }
  ],
  "new_read_collaborators": [],
  "new_write_collaborators": [],
  "quality_check": null
}

**Comment by JChipault** [comment] 2019-09-25 15:42
tried in chrome (didn't think it would matter but also heard that USGS not supporting firefox anymore) and got same thing. 
Error. Event not Submitted. Error message: {"Log-Id":"16d691579dc-f3d414d6","Request Time":"2019-09-25 15:41:18 GMT","Error":"The specified URL cannot be found "}

**Comment by JChipault** [comment] 2019-09-25 15:43
colleague was able to enter 200208 and 200209 around the same time and didn't have a problem

**Comment by aaronstephenson** [comment] 2019-09-25 16:16
Derek from EROS says this should be fixed now. He says the cause was
>It was a JSON Key "history" that was too long. I have to dig a little to see why that didn't fall into the current policies.

@JChipault let us know if you can create the event now.

**Comment by JChipault** [comment] 2019-09-25 16:21
@aaronstephenson I still had the create event page open and I got the same type of error message if I just clicked "Save Event"... do I need to close it out and re-enter everything?

**Comment by aaronstephenson** [comment] 2019-09-25 16:23
I don't know why it wouldn't have just worked, but yeah, please close and re-enter from scratch.

**Comment by JChipault** [comment] 2019-09-25 16:24
I also had it opened in Chrome still and when I re-tried there it went right through (without closing the tab and re-entering)

**Comment by aaronstephenson** [comment] 2019-09-25 16:28
OK. Glad it worked.

So, to elaborate a little on Derek's statement, the reason why your request failed initially was because the value of the "history" field (one of the comment types) was too long for the WAF's liking. It looked like it was 1299 characters, so I'm guessing the WAF was capped at 1000. I suspect the other folks who successfully created events simply had shorter comments.

I'll follow up with Derek to remind him that we specifically told them before to allow unlimited length for all fields.

**Comment by JChipault** [comment] 2019-09-25 16:28
thanks!

**Closed** 2019-09-25 16:35 UTC
Labels: Before Effort 2, bug

**Comment by JChipault** [comment] 2019-09-26 21:37
@aaronstephenson did EROS not change the rules for the test site? Was at https://whisperstest.wim.usgs.gov/event/170772 just now and got this 
![image](https://user-images.githubusercontent.com/49287076/65726964-feaf2080-e07b-11e9-8d11-be3f71bc5001.png)

**Comment by JChipault** [comment] 2019-09-26 22:26
@aaronstephenson just tried it on the live site with 200210 and got same warning. Not letting me submit long comments. 
![image](https://user-images.githubusercontent.com/49287076/65729116-c0692f80-e082-11e9-99d0-428b2fc813bc.png)

**Comment by aaronstephenson** [comment] 2019-09-26 22:28
For Pete's sake... it's maddening that this is still a problem. I'll get in touch with EROS again about this.

Could you try a comment that is 1000 characters or fewer and let me know if that succeeds?

**Comment by JChipault** [comment] 2019-09-27 13:36
yes, smaller comments are going through just fine on both test and live.

**Comment by aaronstephenson** [comment] 2019-09-27 15:09
@JChipault could you try submitting the long comment for event 200210 again? Derek is watching the logs right now and will try to track down what's wrong.

**Comment by JChipault** [comment] 2019-09-27 15:13
@aaronstephenson just tried and still got error. 
![image](https://user-images.githubusercontent.com/49287076/65780460-61053100-e10f-11e9-9099-7276573369bc.png)

**Comment by JChipault** [comment] 2019-09-27 15:14
followed it up by adding a two-word comment and that went through

**Comment by aaronstephenson** [comment] 2019-09-27 17:01
Thanks @JChipault, Derek found the request in the logs and mad some tweaks. Could you try again please?

**Comment by JChipault** [comment] 2019-09-27 17:13
@aaronstephenson looks like it went through!  It's just a test comment with stuff not relevant to that live event so let me know when EROS has done what it needs to do and then I will delete that comment.
