### ISSUE TITLE
species lists in grouped events multiplying

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#713] opened 2019-09-27 20:16 UTC
head to 200206 on the live site, note that it's grouped with 200210. toggle between 206 and 210 and watch the species list change as you toggle back and forth

**Comment by BlakeDraper** [comment] 2019-09-30 19:21
Fixed in code.

**Comment by JChipault** [comment] 2019-11-08 19:54
@BlakeDraper I'm in 2.8.2 and this seems to still be happening. Bummer.
This is 200124 and it should be: 

and it showed up as: 
![image](https://user-images.githubusercontent.com/49287076/68506420-3d192d00-022f-11ea-8fea-986d31d8716e.png)

**Comment by JChipault** [comment] 2019-11-08 19:57
sorry... this is what it should be: 
![image](https://user-images.githubusercontent.com/49287076/68506504-65089080-022f-11ea-90c9-cd9f264c4e0b.png)

However.... I'm trying to reproduce it and, unlike when i first reported this bug, it doesn't multiply species every time I toggle. What you see in the screenshots just happened a few minutes ago and now I can't reproduce it.

**Comment by JChipault** [comment] 2019-11-08 20:01
I continued toggling and at one point during my toggling between grouped events, I got this screen that showed no species at all and it didn't change even after I let it sit to load for 3+ minutes
![image](https://user-images.githubusercontent.com/49287076/68506793-0394f180-0230-11ea-8b4c-1d25075367a1.png)

This happened to me earlier this afternoon as well, where I opened a page and the species never loaded in the public data area until I hit refresh.

**Comment by BlakeDraper** [comment] 2019-11-08 20:05
@JChipault looking into it currently. I do notice right away that it seem the none showing at all only happens when you click the link to the event you are already viewing. Not saying that is ok and we will fix it, but just an FYI.

**Comment by JChipault** [comment] 2019-11-08 20:06
good sleuthing!!!

**Comment by BlakeDraper** [comment] 2019-11-08 20:50
@JChipault I applied a fix that prevents the current event showing from appearing in that list, which I think makes sense anyway. I am having a harder time recreating the duplication of species, even using the same event you are.

**Comment by JChipault** [comment] 2019-11-12 16:12
I can't get it to reproduce this morning. I'll let you know if it pops up again.

**Comment by JChipault** [comment] 2019-11-13 19:49
uh oh, just now saw it on an event that isn't grouped 
![image](https://user-images.githubusercontent.com/49287076/68798596-500b7300-061c-11ea-81f5-b06c9e94d32f.png)

I think the last thing I did was change the number assessed from 5 to 4 for little brown bats. Then I scrolled up to the top of the page and saw that the species info was duplicated.

**Comment by JChipault** [comment] 2019-11-13 19:53
I hit refresh on my browser and it went back to being two lines of species information up top. then I went down and changed number assessed from 4 to 5 on the Blunt Trauma (NOS) suspect species diagnosis and when I scrolled back up I had four lines of species information. So there's something with changing the number assessed that triggers the multiplying of species information in the public table.

**Comment by JChipault** [comment] 2019-11-13 19:58
(FYI - I just added unidentified bat with a rabies diagnosis on purpose so there should now be 3 species listed up top but I added this third species after grabbing the screen shot provided above)

**Comment by JChipault** [comment] 2019-11-13 21:17
Just happened on a different event (200214) that is not in a group after I added a location comment. Was able to reproduce by hitting refresh on the browser to reset it and then adding another comment.

**Comment by JChipault** [comment] 2019-11-18 18:34
@lprivette @BlakeDraper just wondering if you've seen this?

**Comment by lprivette** [comment] 2019-11-18 19:38
I tested on event 200183 and haven't been able to recreate it. I haven't tried editing fields though since it's in production and I really don't want to mess anything up. 

Using firefox in test I've tried to recreate it with event 170717 by adding comments/changing numbers affected field, but no luck.

Since Blake has worked on this issue before he might have a better idea of what's going on, but this seems like a really hard one to track down on my machine.

**Comment by BlakeDraper** [comment] 2019-11-18 19:52
I'll get back at it. I know the cause of the multiplication, but I believed that it was being prevented in all possible cases. It comes down to resetting the array that makes up that list every time the data is refreshed. If it is not reset to blank, it will re-populate it. I'll try to determine what sequence of actions is somehow causing the logic to miss the reset line.

**Comment by BlakeDraper** [comment] 2019-11-18 21:39
Found and fixed. Coming in next release.

**Comment by JChipault** [comment] 2019-11-18 21:41
You guys rock. Thanks!

**Comment by JChipault** [comment] 2022-03-11 22:12
@BlakeDraper  this one popped up again when I was toggling between 201838 and 201849 by clicking the "Associated Events" link. There should only be one row for Canada Goose in this event (per the number "Affected" at the top)

![image](https://user-images.githubusercontent.com/49287076/157978816-97e4808d-e7f9-4405-b95b-ea7e16bd79eb.png)

**Comment by JChipault** [comment] 2022-03-11 22:15
(darn, I just did another late Friday afternoon report into Github! I swear I just ran in to this issue... not that I've been sitting on it until now. Doesn't need to be fixed today, but is a bug that needs stomping again)

**Comment by BlakeDraper** [comment] 2022-06-08 17:54
Squashed again.

Note for future self or other developer: The line `this.eventLocationSpecies = [];` had to be moved down within the `this._eventService.getEventDetails` subscription because higher up within the ngOnInit was still causing it to not properly overwrite to blank array, assuming due to some sort of race condition. There may be a better fix that involves a holistic restructuring of the data handling in this component, but this fix is effective and expedient for the time being.

**Closed** 2022-06-10 18:42 UTC
Labels: bug, Before Effort 2

**Comment by JChipault** [comment] 2022-07-06 14:49
looks good on the test site
